- name: check if Pacemaker service is presented 
  stat:
    path=/etc/systemd/system/pacemaker.service
  register: pacemaker_service_file

- name: stop Pacemaker service if exists
  service:
    name="pacemaker"
    state=stopped
  when: pacemaker_service_file.stat.exists == True
