- name: wait for Pacemaker startup completion
  shell: crmadmin -qS {{ node_name }}
  register: result
  retries: 20
  delay: 5
  changed_when: false
  until: result.rc == 0 and (result.stderr == "S_IDLE" or result.stderr == "S_NOT_DC")
